Finishing up the File Renaming and Moving: - Renamed the FirstPersonProjectile to BallProjectile and put it in a new folder "Weapons" - Be sure to do a project-wide rename, and fix up #include paths for referenced files - reparent the FirstPersonProjectile blueprint - Remove The TP_ThirdPerson Folder since none of the cpp files are needed anymore - Move all the NPC/AI scripts into a new folder "NPC"
-Compile, open level, test it works, Hurray

Fixing Errors:
Error: CDO Constructor (S05_BattleRoyaleGameMode): Failed to find /Game/FirstPersonCPP/Blueprints/FirstPersonCharacter.FirstPersonCharacter_C
Error: CDO Constructor (S05_BattleRoyaleHUD): Failed to find /Game/FirstPerson/Textures/FirstPersonCrosshair

- Find the assets in the content browser>> right click>> Copy the Reference
- find the cpp for BattleRoyaleGameMode and BattleRoyaleHUD and replace the file path with the Assets new filepath
- Take out he extra quotes and make it look the same as the previous line